"use client";

import "./globals.css";
import { useEffect } from "react";

export default function RootLayout({ children }) {
  useEffect(() => {
    // Инициализация Telegram WebApp только на клиенте
    if (typeof window !== "undefined" && window.Telegram?.WebApp) {
      const tg = window.Telegram.WebApp;
      tg.expand();
      tg.ready();

      // Скрываем основную кнопку, так как закрытие происходит через TopControls
      tg.MainButton.hide();

      // Настраиваем кнопку "Назад"
      tg.BackButton.onClick(() => {
        window.history.back();
      });

      console.log("Telegram WebApp initialized");
    }
  }, []);

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <title>Yandex TMA</title>
        <meta name="description" content="Generated by create next app" />
        <script src="https://telegram.org/js/telegram-web-app.js"></script>
      </head>
      <body>
        <main className="container">{children}</main>
      </body>
    </html>
  );
}
